### ISSUE TITLE
backend function benchmark 

### ISSUE THREAD

**Issue by jspaaks** [benvanwerkhoven/kernel_tuner#13]
[c.py](https://github.com/benvanwerkhoven/kernel_tuner/blob/dc2cbc4ed50b806478e3b1264e9a3be73a405f3d/kernel_tuner/c.py#L172-L222), [cuda.py](https://github.com/benvanwerkhoven/kernel_tuner/blob/dc2cbc4ed50b806478e3b1264e9a3be73a405f3d/kernel_tuner/cuda.py#L121-L161), and [opencl.py](https://github.com/benvanwerkhoven/kernel_tuner/blob/dc2cbc4ed50b806478e3b1264e9a3be73a405f3d/kernel_tuner/opencl.py#L93-L130) 
1. returning the ``times`` array would offer more flexibility than returning the mean of ``times[1:-1]``, e.g. when you're interested in the distribution of the times required.
1. variable ``iterations`` seems to be more at home as ``.benchmark(self, func, gpu_args, threads, grid, iterations=7)`` than as an instance variable (``self.iterations``)
1. if [the times[1:-1] construct](https://github.com/benvanwerkhoven/kernel_tuner/blob/dc2cbc4ed50b806478e3b1264e9a3be73a405f3d/kernel_tuner/opencl.py#L130) is to remain, we should add a check that ``assert len(times) >= 3, "not enough iterations."``
1. it is currently not possible to adjust the number of iterations of a benchmark using the public interface

**Comment by benvanwerkhoven** [comment]
1. yeah I agree, I also had that at some point in branch, but never merged those changes. 
2. true, except for the fact that it does not make sense to use a different number of iterations every time you call benchmark.
3. when we return an array of times removing the fastest and slowest runs can be something that the user may want to do themselves.
4. I'm fine with adding an option to tune_kernel for this.

**Comment by benvanwerkhoven** [comment]
What I want for this issue is to return the average as we have now as 'time' in the tuning results. But in addition to that we can return all measured execution times using for example the name 'times'. 

The iterations option has been added to public interface. Checking that it's at least 3, or not compute the average in that way if it's less than three is still a good idea.

**Comment by isazi** [comment]
As part of the sprint, I would like to check this issue and see if I can work on it.

**Comment by isazi** [comment]
Made a branch with the change. All tests are passing, and I added two tests for the times.
