### ISSUE TITLE
get_config_string trailing comma

### ISSUE THREAD

**Issue by jspaaks** [benvanwerkhoven/kernel_tuner#14]
https://github.com/benvanwerkhoven/kernel_tuner/blob/dc2cbc4ed50b806478e3b1264e9a3be73a405f3d/kernel_tuner/util.py#L16

what you probably want is:
```python
return ", ".join([k + "=" + str(v) for k, v in params.items()])
```
(gets rid of the trailing comma)

**Comment by benvanwerkhoven** [comment]
sure! this could have been just a pull request ;-)

**Comment by jspaaks** [comment]
OK, I was trying to follow the procedure of
1. making an issue
1. wait for the go-ahead (or otherwise)
1. then start work
1. have the PR accepted
