### ISSUE TITLE
put functions in alphabetical order

### ISSUE THREAD

**Issue by jspaaks** [benvanwerkhoven/kernel_tuner#16]
I asked around (during one of our clean coding sessions) what people think one should do regarding the ordering of methods/functions. In the Java world at least, the 'right' way of doing it is to order them depending on what level a fucntion is on in the callgraph (I find that confusing BTW). This leaves me unsure how to resolve this issue. Regardless, I still think it would be a good idea to have some kind of ordering in the function names. I leave it up to you wether to pursue this or not.

**Comment by benvanwerkhoven** [comment]
For files that contain more than just a couple of functions it makes sense to have at least some ordering, alphabetically probably makes the most sense. I've sorted the 20 functions in util.py and the 11 functions in core.py alphabetically. See commit c4d20486219416f316fe85ba750549b655368b58.
