### ISSUE TITLE
Failure in `test_kernelbuilder`

### ISSUE THREAD

**Issue by isazi** [benvanwerkhoven/kernel_tuner#165]
There is an inconsistency in `test_kernelbuilder`: two of the tests use the CuPy backend, but they are skipped if PyCUDA is not installed. This cause issues of tests failing if PyCUDA is installed but not CuPy, and at the same time the two tests are skipped if PyCUDA is not installed.

There are two possible fixes:
1) Keep the CuPy backend enabled, but skip if CuPy is not installed;
2) Change backend to PyCUDA.

Which solution do you prefer?

**Comment by benvanwerkhoven** [comment]
I think it would make sense to test it with either backend. We could use ``@pytest.mark.parametrize`` to iterate over the backends. To ensure that the test is skipped when a backend is not installed we can still call ``pytest.skip`` instead of using the decorator ``@pytest.mark.skip``.

**Comment by benvanwerkhoven** [comment]
Thanks this is solved now by your pull request, closing the issue!
