### ISSUE TITLE
can we merge util.py into core.py?

### ISSUE THREAD

**Issue by jspaaks** [benvanwerkhoven/kernel_tuner#17]
the current sepration is not helping me find things better. Merging the two would remove one degree of freedom at least.

**Comment by benvanwerkhoven** [comment]
The idea for the current separation is as follows: If a function needs to do anything with the current device, in other words, if a function is talking to the backend, it belongs in core. You can see this distinction in practice with 'dev' being the first argument of every function in core. Core should be seen as the high-level interface that wraps the lower-level device function interfaces.

If a function doesn't have 'dev' as it's first argument, it's not in core. It's just a utility function that could be used anywhere in the Kernel Tuner internally and should therefore be in put util. 

Why do you think this is so unclear?

Also, merging util and core right now would create circular dependencies. As core imports the low-level device functions interfaces, which in turn use utility functions in util that therefore can not be in core.
