### ISSUE TITLE
avoid ambiguity of original_kernel

### ISSUE THREAD

**Issue by jspaaks** [benvanwerkhoven/kernel_tuner#18]
currently, ``original_kernel`` ([here](https://github.com/benvanwerkhoven/kernel_tuner/blob/dc2cbc4ed50b806478e3b1264e9a3be73a405f3d/kernel_tuner/util.py#L18-L26), [here](https://github.com/benvanwerkhoven/kernel_tuner/blob/dc2cbc4ed50b806478e3b1264e9a3be73a405f3d/kernel_tuner/util.py#L41-L59), and [here](https://github.com/benvanwerkhoven/kernel_tuner/blob/dc2cbc4ed50b806478e3b1264e9a3be73a405f3d/kernel_tuner/util.py#L78-L90)) can be either a filename or a string, while [here](https://github.com/benvanwerkhoven/kernel_tuner/blob/dc2cbc4ed50b806478e3b1264e9a3be73a405f3d/kernel_tuner/util.py#L170-L178) and [here](https://github.com/benvanwerkhoven/kernel_tuner/blob/dc2cbc4ed50b806478e3b1264e9a3be73a405f3d/kernel_tuner/util.py#L209-L214), only a string is expected. I think it's more clear to have arguments that are one thing only. This makes it easier to reason about code. It can be easily achieved by having a ``kernel_string`` argument, which is always a string, and a (new) argument, ``kernel_filename`` or something, which is always a filename. Both should be set to ``None`` by default, the user can then overwrite one of them with a non-default value. 

For inspiration, look [here](https://github.com/jspaaks/kernel_tuner/blob/4c8843739f09efeba4133b84cc160a2daf0242f3/kernel_tuner/KernelWrapperAbstract.py#L113-L124).

the function interfaces would then become:
```python
# old 
def detect_language(lang, original_kernel) 
# new
def detect_language(lang, kernel_string)

# old 
def looks_like_a_filename(original_kernel)
# new
# no longer needed

# old
def get_kernel_string(original_kernel)
# new
def get_kernel_string(kernel_string=None, kernel_filename=None)

# old
def prepare_kernel_string(original_kernel, params, grid=(1, 1, 1))
# new
def prepare_kernel_string(kernel_string, params, grid=(1, 1, 1))

# old
def setup_kernel_strings(kernel_name, original_kernel, params, grid)
# new
def setup_kernel_strings(kernel_name, kernel_string, params, grid)
```

**Comment by benvanwerkhoven** [comment]
I agree that the ambiguity should be avoided when possible, and with the fact that the name kernel_string is sometimes ambiguous, because it could still contain either a string or a filename.

One thing to keep in mind is that Python is a dynamically typed language for a reason. And I believe we should keep offering the currently flexibility of passing either a string (be it code or a filename) or a list of filenames in the positional argument of the functions in the user interface. This is a very common thing to do in Python. 

With this in mind, there will be some ambiguity in the name of this positional argument, at least for as long as we haven't treated it as either a code string or a filename yet. I think we should stick to the following naming scheme: 
- original_kernel: as long as we haven't established the type of the argument
- kernel_string: when we've established a string is passed or when the contents of the named file have been read and put into a string
- kernel_filename: use this only very briefly between detecting that original_kernel is actually a filename and not a code string and reading the contents of this file into the kernel_string

**Comment by jspaaks** [comment]
About dynamically typed arguments in Python. I know that it's _allowed_ to have an argument be one of two things. I just think that this is not a good place to use that freedom (I can't think of an instance where it would be useful, but perhaps those cases exist). For me, this becomes clear once you try to give arguments a proper name. For example, if a given function argument can be an apple or an orange, the argument name might end up to be ``apple_or_orange``. In the extreme case, every function may have just one argument ``all_the_things``, that contains, well, all the things, while the function body would then need to contain code to figure out what the heck was passed to the function. To me, this is not a pattern that leads to readable code. 

As an alternative, the ``apple_or_orange`` function could have two input arguments, ``apple`` and ``orange``, both initialized with a default value of ``None``. Then a reader always know what it is that was passed to the function. See my earlier 'inspiration' example. 

So that's my two cents about using the freedom that dynamic typing offers.

Then on to my second point, specifically the name ``original_kernel``. To me, ``original_kernel`` is basically a variation of having one of these cases:

- ``kernel`` and ``new_kernel``
- ``kernel`` and ``kernel2``
- ``old_kernel`` and ``kernel``

I think this pattern should be avoided.

I hope I was able to convince you. If not, feel free to close the issue.

**Comment by benvanwerkhoven** [comment]
I do understand your concerns with the practice of having one argument that can be different things. And it certainly leads to `apple_or_orange` argument names, for example see the `filepath_or_buffer` argument of `pandas.read_csv` here:
https://pandas.pydata.org/pandas-docs/stable/generated/pandas.read_csv.html

While this could be done through two optional arguments filepath= or buffer=, in which you won't need code to figure out what type was being passed, but you would again need code to check that either argument is passed and not both.

Also for the filepath=, you can see that Pandas supports strings, but also `pathlib.Path` and `py._path.local.LocalPath`. This is pattern of supporting arguments of different types that in the end all refer to the same thing offers the user great flexibility and indeed poses additional burden on the library implementer. However, this is to my understanding, the most common way to make user interfaces in Python.

That is why I do believe we should stick to one positional argument that supports both strings and filenames. However, the name `original_kernel` is certainly ambiguous and I agree that it would be better to be explicit about what this argument is and call it something like `kernel_string_or_filenames`.
