### ISSUE TITLE
check tunable parameters for special names that should not be used

### ISSUE THREAD

**Issue by benvanwerkhoven** [benvanwerkhoven/kernel_tuner#19]
The user can decide on their own names for tunable parameters, but some names will lead to errors because they are also used by the tuner internally.

These include 'time', 'times', which are used by the tuner to report output back to the user.

The parameters 'grid_size_x', 'grid_size_y', and 'grid_size_z' are inserted into the code as C-preprocessor defines, if the user also uses these names for their tunable parameters I'm pretty sure it should lead to compile errors. 

The idea is to check the tunable parameters to not contain these reserved keywords when the user calls tune_kernel and report a user-friendly error when if they do.

**Comment by egpbos** [comment]
I'll start working on this.

**Comment by benvanwerkhoven** [comment]
One thing to add to this issue, we should also give a warning when none of the block size names are specified.

It can happen that a user decides to use other names than "block_size_x" and so on, but forgets to specify the block_size_names= option. If none of the block_size_names (default of non-default) are used in the tunable parameters, we can be almost sure the user is making a mistake.
