### ISSUE TITLE
check if the list of arguments supplied matches kernel signature

### ISSUE THREAD

**Issue by benvanwerkhoven** [benvanwerkhoven/kernel_tuner#20]
This issue will be a bit more work as it requires that we inspect the code being passed to the tuner, which could be CUDA, OpenCL, or C code.

We know the name of the function to be called so we can check if the signature of the kernel begin called actually corresponds with the number of arguments and whether the data types match with the argument list that has been passed by the user.

There is already a check_argument_list function, but that currently only checks whether the user has supplied numpy objects. The idea is to check whether the type (for example numpy.ndarray with dtype=numpy.float32) actually matches the argument to the kernel (for example float *).

Also check whether we need to do anything special in case the user supplies a code generating function rather than a string of source code or a filename.

**Comment by isazi** [comment]
Working on this.

**Comment by isazi** [comment]
The new code works and passes tests. Still need to work on the case of code generating functions.

**Comment by isazi** [comment]
Ready to merge. At the moment the feature is supported only for code supplied as string or file, not for code generators.

**Comment by benvanwerkhoven** [comment]
Thanks!

**Comment by isazi** [comment]
Improve the parsing of the function.

**Comment by isazi** [comment]
Superseded by issue #57
