### ISSUE TITLE
simplify installation process

### ISSUE THREAD

**Issue by benvanwerkhoven** [benvanwerkhoven/kernel_tuner#22]
We can use the 'extras' feature inside setup.py to specify a number of extras that require optional dependencies.

Kernel Tuner has several optional dependencies, for example you could only be interested in tuning CUDA kernels, so it would not make sense to require OpenCL to be installed, or vice versa. You can read more about this in the [install guide](https://github.com/benvanwerkhoven/kernel_tuner/blob/master/INSTALL.rst).

The idea is to turn these optional depencies into extras such that the user can install Kernel Tuner in a single command, instead of first installing Kernel Tuner and then having to also install all optional dependencies.

Currently we have a file called requirements-dev.txt for all the dependencies that are required to start developing Kernel Tuner. These could also be integrated using an 'extra'.

Please don't forget to update the install and contribution guides accordingly when you work on this issue.

**Comment by felipeZ** [comment]
Using the [extras_require](http://setuptools.readthedocs.io/en/latest/setuptools.html#declaring-extras-optional-features-with-their-own-dependencies) for the [Setuptools](http://setuptools.readthedocs.io/en/latest/setuptools.html#declaring-extras-optional-features-with-their-own-dependencies) the new optional keywords for installation have been added:
 *  doc: install requirements to build the documentation.
 * cuda: install [pycuda](https://documen.tician.de/pycuda/) dependency.  
 * opencl: install [pyopencl](https://mathema.tician.de/software/pyopencl/) dependency.
* tutorial: install dependencies to run the [jupyter notebooks](https://github.com/benvanwerkhoven/kernel_tuner/tree/master/tutorial) interactively.
* dev: install all the libraries to further develop `kernel_tuner`.
