### ISSUE TITLE
minimum CUDA and OpenCL versions in the documentation 

### ISSUE THREAD

**Issue by ipelupessy** [benvanwerkhoven/kernel_tuner#34]
maybe I am overlooking things, but what is your (minimum) targeted CUDA and OpenCL versions? 

I could run the examples with openCL 1.1 with a minor fix (#33), but I am not sure this is ok

**Comment by isazi** [comment]
This issue is marked as "Done" in the project, but still open among the issues. Should it be closed or not?

**Comment by ipelupessy** [comment]
for me its ok..
