### ISSUE TITLE
Generate images for the diffusion tutorial

### ISSUE THREAD

**Issue by felipeZ** [benvanwerkhoven/kernel_tuner#35]
In the current tutorial the images in the [difussion tutorial](http://benvanwerkhoven.github.io/kernel_tuner/diffusion.html) are not rendered properly, probably because the jupyter notebook was not saved in an state where all the cells were evaluated.
The Jupyter notebook needs to be run and the docs update.

**Comment by benvanwerkhoven** [comment]
Thanks!
