### ISSUE TITLE
in cuda.py compiler_options = ['-Xcompiler=-Wall'] not used

### ISSUE THREAD

**Issue by ipelupessy** [benvanwerkhoven/kernel_tuner#37]
source seems to suggest the following compiler option should be used:
```
compiler_options = ['-Xcompiler=-Wall'] 
```
later on self.compiler_options is added, but then in the compile:
```
self.current_module = source_mod(kernel_string, options=self.compiler_options + ["-e", kernel_name],
                                               arch='compute_' + self.cc, code='sm_' + self.cc,
                                               cache_dir=False, no_extern_c=no_extern_c)
```
ie self.compiler_options is used. maybe check whether option is needed and correct accordingly..

**Comment by benvanwerkhoven** [comment]
@ipelupessy already fixed this in commit 492274bd432b4609a46d2b3cb8622add0523f943
Thanks!
