### ISSUE TITLE
use readthedocs for generating documentation

### ISSUE THREAD

**Issue by benvanwerkhoven** [benvanwerkhoven/kernel_tuner#41]

**Comment by benvanwerkhoven** [comment]
Hi Patrick, I'm not sure how far you were with preparations for this, but I'd like to try to set it up now. I hear it's very easy to setup, so I'll just go ahead.

**Comment by egpbos** [comment]
It's already done http://kernel-tuner.readthedocs.io/en/latest/

**Comment by benvanwerkhoven** [comment]
Haha ok! Never mind ;-)

**Comment by benvanwerkhoven** [comment]
One very big bummer is that there's now ads on the documentation pages, I had not realized that

**Comment by egpbos** [comment]
Note that, apart from some minimal configuration on readthedocs.org, the one thing that had to be changed in the code is the addition of a requirements.txt file. I put this in the readthedocs branch for the time being. If we decide to use readthedocs.org, the readthedocs branch could be merged into master and the readthedocs.org configuration should be updated to base the build on the master branch. Also, it would be useful to activate Github webhooks then, which I don't have permissions for.

**Comment by benvanwerkhoven** [comment]
Since we're trying the alternative, I'll close this issue for the time being
