### ISSUE TITLE
faster build in travis

### ISSUE THREAD

**Issue by felipeZ** [benvanwerkhoven/kernel_tuner#44]
In order to speed up the building in **Travis** we need to remove the `sudo` dependency from the `.travis.yml` file. This allow to use the faster docker stack offer by **Travis CI**.
See [the travis blog](https://blog.travis-ci.com/2014-12-17-faster-builds-with-container-based-infrastructure/), for further explanations.

**Comment by egpbos** [comment]
This can now be closed right?

**Comment by felipeZ** [comment]
Yes
