### ISSUE TITLE
update correctness verification documentation 

### ISSUE THREAD

**Issue by benvanwerkhoven** [benvanwerkhoven/kernel_tuner#49]
This document should be updated to include the description of a feature, which is the verify option. This option allows users to specify their own functions for performing output verification. The current article can be found here: http://benvanwerkhoven.github.io/kernel_tuner/correctness.html

An example of how to use the new verify option can be found in the reduction example.

**Comment by isazi** [comment]
Added an explanation of the "verify" option of "tune_kernel()".
