### ISSUE TITLE
use more advanced parsing for argument lists

### ISSUE THREAD

**Issue by benvanwerkhoven** [benvanwerkhoven/kernel_tuner#57]
Currently the argument checker only looks for the first pair of braces "(" and ")", we should do something a little bit more advanced and try to really get the argument list. Note that just looking for the first occurrence of the kernel name is not safe enough either, the name itself could appear in multiple places as a substring of something else, or inside a comment.

So depending on the language it would be best to look for something like "__kernel" <any amount of whitespace including newlines> "void" <again white space > "kernel_name" <whitespace possibly> "(" comma-separated argument list ")". Multiline regexes are probably what we need.

**Comment by isazi** [comment]
Didn't see this until now.

**Comment by isazi** [comment]
Code committed.
