### ISSUE TITLE
Noodles Runner - dict result workaround

### ISSUE THREAD

**Issue by benvanwerkhoven** [benvanwerkhoven/kernel_tuner#6]
Noodles runner can only work with tuple currently, but we want a dictionary as a result so this needs to be constructed in the run function.

**Comment by benvanwerkhoven** [comment]
@bpmweel I'm currently working on integrating the Noodles runner into the master branch. Any updates on this issue?

**Comment by bpmweel** [comment]
@benvanwerkhoven Sorry I have not gotten around to doing it. Perhaps I can schedule some time next week to do it.

**Comment by benvanwerkhoven** [comment]
I don't think the issue still exists with the last rewriting of the noodles runner. Closing this for now.
