### ISSUE TITLE
add pep8 to dev tools

### ISSUE THREAD

**Issue by jspaaks** [benvanwerkhoven/kernel_tuner#7]
something along the lines of 
```
pip install pytest-pep8
```
or 
```
pip install pylint
```
- make code pep8 compliant (currently, the pylint score is just over 50%)
- add pep8 to the 'how to contribute' documentation

**Comment by benvanwerkhoven** [comment]
We already have codacy that runs pylint and checks for many things. I'm fine with adding pylint to the dev requirements.

As for the contribution guide, we already state that we plan to adhere to the Google Python Style guide, do you think pep8 is better or more complete than the Google Python Style guide? I think we should choose a style guide and not aim to enforce multiple ones.

I went through codacy's settings and I've changed a couple of settings to made the checks stricter. However, most things pylint complaints about are bad white space, which should be easy to fix. 

It also seems that a lot of the things that pylint complaints about are just false:

> E: 36, 8: Module 'pycuda.driver' has no 'init' member (no-member)
E: 37,23: Module 'pycuda.driver' has no 'Device' member (no-member)
E: 50,56: Module 'pycuda.driver' has no 'get_version' member (no-member)

>E: 89,28: Module 'numpy' has no 'float32' member (no-member)
E: 90,28: Module 'numpy' has no 'float64' member (no-member)

Obviously, these members of numpy and pycuda.driver do exist. I'm not sure how representative the pylint score really is at this point.

Anyway, I'll go over the list and fix most things. I've seen a few things that codacy also complaints about.

**Comment by benvanwerkhoven** [comment]
Fixed most of this in commits d1fb7232 and 425c6fce.

Regarding the PEP8 vs Google Python Style Guide issue:

Google Python Style Guide requires people to use pylint, among many other code style recommendations. Pylint checks for PEP8, among several other things. Since we already state in the contribution guide that we adhere to the Google Python Style Guide, PEP8 is implied.

**Comment by jspaaks** [comment]
Good stuff. Maybe also add a line to the contributing guidelines about how people should run pylint before making a pull request (or actually, before making a commit)

**Comment by benvanwerkhoven** [comment]
Sure! Good idea!
