### ISSUE TITLE
add pytest.ini file or tool:pytest section in setup.cfg

### ISSUE THREAD

**Issue by jspaaks** [benvanwerkhoven/kernel_tuner#8]
(to be explicit about the test configuration)

**Comment by benvanwerkhoven** [comment]
Why do you think we need pytest.ini when we are not requiring anything special from pytest? We don't even have any command line options when calling pytest.

setup.cfg configures the behavior of the various setup commands when installing the project. You don't need pytest to install the Kernel Tuner, why do you think we should change this?

**Comment by jspaaks** [comment]
I prefer to be explicit about the test setup, even when the tool is using the default directory to look for tests, and the globbing pattern it's using is the default pattern.

I guess there are two schools of thought about this, some people think that as long as you're doing 'the normal thing' there's no need to be explicit about it. I disagree with this, because my normal thing may not be your normal thing. So, I'm firmly in one school, but if you are in the other, feel free to close the issue.
