### ISSUE TITLE
interface.py superfluous?

### ISSUE THREAD

**Issue by jspaaks** [benvanwerkhoven/kernel_tuner#9]
__init__.py is the public interface AFAIK (e.g. https://www.reddit.com/r/Python/comments/1bbbwk/whats_your_opinion_on_what_to_include_in_init_py/), no need for interface.py

**Comment by benvanwerkhoven** [comment]
While it's true that __init__.py is the public interface, and interface.py is the only module from which stuff is included, it is actually not common practice to have anything more than a couple of includes in __init__.py. In addition, it is also likely that as the functionality of the Kernel Tuner expands in the near future, __init__.py will then include functions from multiple files. When this happens, it will be a good idea to rename interface.py to something that better reflects its content (functions for testing and tuning kernels).

http://docs.python-guide.org/en/latest/writing/structure/
> A commonly seen issue is to add too much code to __init__.py files. When the project complexity grows, there may be sub-packages and sub-sub-packages in a deep directory structure. In this case, importing a single item from a sub-sub-package will require executing all __init__.py files met while traversing the tree.
Leaving an __init__.py file empty is considered normal and even a good practice, if the package’s modules and sub-packages do not need to share any code.
